apiVersion: v1
kind: Service
metadata:
  name: adm-painel-service
  namespace: administration-painel
spec:
  selector:
    app: adm-painel
  type: NodePort
  ports:
    - name: application
      protocol: TCP
      port: 5000
      targetPort: 5000